# Generated by Django 4.2.15 on 2024-08-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(default='', max_length=20)),
                ('Last_name', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Password', models.CharField(default='', max_length=12)),
                ('Confirm_password', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_name', models.CharField(default='', max_length=20)),
                ('Project_head', models.CharField(default='', max_length=20)),
                ('Project_startdate', models.DateField(blank=True, null=True)),
                ('Project_enddate', models.DateField(blank=True, null=True)),
                ('project_members', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
